<<<<<<< HEAD
=======
'''Alexandros Frangiadoulis 11/01/2021 '''


>>>>>>> c1b7500202f28ca28b6a109360763fd79a822f04
import pandas as pd
import itertools
from  itertools import permutations
import time



class all_combos(object):
    
    def __init__(self):
                 
<<<<<<< HEAD
        self.names               =  ['4ART', 'USDT', 'AAPL', 'USD', 'AAVE', 'ETH', 'EUR', 'ABBC', 'ABYSS', 'ACXT', 'ADABEAR', 'ADA', 'ADABULL', 'ADK', 'ADT', 'ADX', 'AEON', 'AID', 'AKN', 'AKRO', 'ALGO', 'AMP', 'AMZN', 'ANKR', 'ANT', 'APM', 'AR', 'ARDR', 'ARK', 'ATOM', 'BABA', 'BAL', 'BAND', 'BAT', 'BBC', 'BCH', 'BEAR', 'BFT', 'BILI', 'BLK', 'BLOCK', 'BNT', 'BNTX', 'BOA', 'BORA', 'BRZ', 'BSV', 'BTC', 'BTCV', 'BTE', 'BTM', 'BTS', 'BTT', 'BTU', 'BULL', 'BURST', 'BWF', 'BWX', 'BYND', 'CAMP', 'CBC', 'CELO', 'CGT', 'CHR', 'CKB', 'CND', 'CNS', 'CNTM', 'COMP', 'COSM', 'CPC', 'CRO', 'CRW', 'CTC', 'CTXC', 'CURE', 'CUSD', 'CVC', 'CVT', 'DAI', 'DASH', 'DAWN', 'DCR', 'DEP', 'DFI', 'DGB', 'DMT', 'DNA', 'DNT', 'DOGE', 'DOT', 'DRGN', 'DTA', 'DUCATO', 'DUSK', 'ECELL', 'ECOC', 'EDR', 'ELA', 'ELAMA', 'EMC2', 'ENG', 'ENJ', 'EOS', 'ETC', 'ETHBEAR', 'ETHBULL', 'EXCL', 'EXE', 'EXP', 'FB', 'FCT2', 'FCT', 'FIL', 'FIRO', 'FIT', 'FLETA', 'FLO', 'FME', 'FNB', 'FOR', 'FRSP', 'FSN', 'FTC', 'FX', 'GAME', 'GBYTE', 'GEO', 'GLEEC', 'GLM', 'GNC', 'GNO', 'GO', 'GOOGL', 'GRIN', 'GRS', 'GRT', 'GST', 'GTO', 'GXC', 'HBAR', 'HBD', 'HDAC', 'HDAO', 'HEDG', 'HIVE', 'HMQ', 'HNS', 'HXRO', 'HYDRO', 'ICX', 'IGNIS', 'INSTAR', 'INX', 'IOC', 'IOST', 'IOTA', 'IOTX', 'IRIS', 'JNT', 'KAI', 'KDA', 'KDAG', 'KLAY', 'KLV', 'KMD', 'KNC', 'KOK', 'KRT', 'KSM', 'LAMB', 'LBC', 'LCS', 'LINK', 'LMCH', 'LOKI', 'LOOM', 'LOON', 'LRC', 'LSK', 'LTC', 'LUCY', 'LUNA', 'MAID', 'MANA', 'MARO', 'MATIC', 'MDT', 'ME', 'MED', 'MEME', 'MER', 'META', 'MET', 'MFA', 'MFT', 'MKR', 'MOC', 'MOF', 'MONA', 'MORE', 'MRPH', 'MTL', 'MUE', 'NAV', 
'NEO', 'NFLX', 'NGC', 'NKN', 'NLG', 'NMR', 'NPXS', 'NVT', 'NXS', 'NXT', 'OCEAN', 'OGN', 'OK', 'OMG', 'ONG', 'ONT', 'ORBS', 'OXT', 'PART', 'PAX', 'PAY', 'PFE', 'PHNX', 'PI', 'PINK', 'PIVX', 'PLA', 'PMA', 'POT', 'POWR', 'PPC', 'PROM', 'PTON', 'PTOY', 'PXL', 'QLC', 'QNT', 'QRL', 'QTUM', 'RCN', 'RDD', 'REN', 'RENBTC', 'REPV2', 'REV', 'RLC', 'RVC', 'RVN', 'SBD', 'SC', 'SDT', 'SENSO', 'SG', 'SHR', 'SIB', 'SIX', 'SKM', 'SLS', 'SNT', 'SOLVE', 'SPC', 'SPHR', 'SPIN', 'SPND', 'SPY', 'SRN', 'STC', 'STEEM', 'STMX', 'STORJ', 'STPT', 'STRAX', 'SUKU', 'SUTER', 'SXP', 'SYS', 'TEA', 'TEMCO', 'THC', 'TNC', 'TRAC', 'TRX', 'TRYB', 'TSHP', 'TSLA', 'TUBE', 'TUDA', 'TUSD', 'UBQ', 'UBT', 'UCT', 'UMA', 'UNI', 'UPEUR', 'UPP', 'UPT', 'UPUSD', 'UPXAU', 'UQC', 'URAC', 'USDC', 'USDN', 'USDS', 'UST', 'UTI', 'UTK', 'VAL', 'VANY', 'VBK', 'VDX', 'VEE', 'VET', 'VIA', 'VIB', 'VID', 'VITE', 'VLX', 'VRA', 'VRC', 'VTC', 'WAVES', 'WAXP', 'WBTC', 'WGP', 'WICC', 'WINGS', 'XDN', 'XEM', 'XHV', 'XLM', 'XMR', 'XMY', 'XRP', 'XST', 'XTP', 'XTZ', 'XUC', 'XVG', 'XWC', 'YFL', 'YOU', 'ZEC', 'ZEN', 'ZIL', 'ZRX']     
        self.all_triangles       = []
        self.unique_combinations = []
        self.possible_combinations = [ '4ART-BTC'
                                      ,'4ART-USDT'
                                      ,'AAPL-BTC'
                                      ,'AAPL-USD'
                                      ,'AAPL-USDT'
                                      ,'AAVE-BTC'
                                      ,'AAVE-ETH'
                                      ,'AAVE-EUR'
                                      ,'AAVE-USD'
                                      ,'AAVE-USDT'
                                      ,'ABBC-BTC'
                                      ,'ABYSS-BTC'
                                      ,'ACXT-USDT'
                                      ,'ADABEAR-USD'
                                      ,'ADABEAR-USDT'
                                      ,'ADA-BTC'
                                      ,'ADABULL-USD'
                                      ,'ADABULL-USDT'
                                      ,'ADA-ETH'
                                      ,'ADA-EUR'
                                      ,'ADA-USD'
                                      ,'ADA-USDT'
                                      ,'ADK-BTC'
                                      ,'ADT-BTC'
                                      ,'ADX-BTC'
                                      ,'ADX-ETH'
                                      ,'AEON-BTC'
                                      ,'AID-BTC'
                                      ,'AKN-BTC'
                                      ,'AKN-USDT'
                                      ,'AKRO-BTC'
                                      ,'ALGO-BTC'
                                      ,'ALGO-USD'
                                      ,'ALGO-USDT'
                                      ,'AMP-BTC'
                                      ,'AMZN-BTC'
                                      ,'AMZN-USD'
                                      ,'AMZN-USDT'
                                      ,'ANKR-BTC'
                                      ,'ANKR-ETH'
                                      ,'ANT-BTC'
                                      ,'ANT-ETH'
                                      ,'APM-BTC'
                                      ,'APM-USDT'
                                      ,'AR-BTC'
                                      ,'ARDR-BTC'
                                      ,'ARK-BTC'
                                      ,'ATOM-BTC'
                                      ,'ATOM-ETH'
                                      ,'ATOM-USD'
                                      ,'ATOM-USDT'
                                      ,'BABA-BTC'
                                      ,'BABA-USD'
                                      ,'BABA-USDT'
                                      ,'BAL-BTC'
                                      ,'BAL-ETH'
                                      ,'BAL-EUR'
                                      ,'BAL-USD'
                                      ,'BAL-USDT'
                                      ,'BAND-BTC'
                                      ,'BAND-ETH'
                                      ,'BAND-EUR'
                                      ,'BAND-USD'
                                      ,'BAND-USDT'
                                      ,'BAT-BTC'
                                      ,'BAT-ETH'
                                      ,'BAT-USD'
                                      ,'BAT-USDT'
                                      ,'BBC-BTC'
                                      ,'BBC-USDT'
                                      ,'BCH-BTC'
                                      ,'BCH-ETH'
                                      ,'BCH-EUR'
                                      ,'BCH-USD'
                                      ,'BCH-USDT'
                                      ,'BEAR-USD'
                                      ,'BEAR-USDT'
                                      ,'BFT-BTC'
                                      ,'BILI-BTC'
                                      ,'BILI-USD'
                                      ,'BILI-USDT'
                                      ,'BLK-BTC'
                                      ,'BLOCK-BTC'
                                      ,'BNT-BTC'
                                      ,'BNT-ETH'
                                      ,'BNTX-BTC'
                                      ,'BNTX-USD'
                                      ,'BNTX-USDT'
                                      ,'BOA-BTC'
                                      ,'BOA-USDT'
                                      ,'BORA-BTC'
                                      ,'BRZ-BTC'
                                      ,'BRZ-USDT'
                                      ,'BSV-BTC'
                                      ,'BSV-ETH'
                                      ,'BSV-EUR'
                                      ,'BSV-USD'
                                      ,'BSV-USDT'
                                      ,'BTC-EUR'
                                      ,'BTC-USD'
                                      ,'BTC-USDT'
                                      ,'BTCV-BTC'
                                      ,'BTCV-USDT'
                                      ,'BTE-BTC'
                                      ,'BTE-USDT'
                                      ,'BTM-BTC'
                                      ,'BTS-BTC'
                                      ,'BTT-BTC'
                                      ,'BTT-USDT'
                                      ,'BTU-BTC'
                                      ,'BULL-USD'
                                      ,'BULL-USDT'
                                      ,'BURST-BTC'
                                      ,'BWF-BTC'
                                      ,'BWF-USDT'
                                      ,'BWX-BTC'
                                      ,'BYND-BTC'
                                      ,'BYND-USD'
                                      ,'BYND-USDT'
                                      ,'CAMP-BTC'
                                      ,'CAMP-USDT'
                                      ,'CBC-USDT'
                                      ,'CELO-BTC'
                                      ,'CELO-ETH'
                                      ,'CELO-USD'
                                      ,'CELO-USDT'
                                      ,'CGT-BTC'
                                      ,'CGT-USDT'
                                      ,'CHR-BTC'
                                      ,'CKB-BTC'
                                      ,'CKB-USDT'
                                      ,'CND-BTC'
                                      ,'CNS-BTC'
                                      ,'CNS-USDT'
                                      ,'CNTM-BTC'
                                      ,'CNTM-USDT'
                                      ,'COMP-BTC'
                                      ,'COMP-ETH'
                                      ,'COMP-USD'
                                      ,'COMP-USDT'
                                      ,'COSM-BTC'
                                      ,'CPC-BTC'
                                      ,'CRO-BTC'
                                      ,'CRO-ETH'
                                      ,'CRO-EUR'
                                      ,'CRO-USD'
                                      ,'CRO-USDT'
                                      ,'CRW-BTC'
                                      ,'CTC-BTC'
                                      ,'CTXC-BTC'
                                      ,'CURE-BTC'
                                      ,'CUSD-BTC'
                                      ,'CUSD-USDT'
                                      ,'CVC-BTC'
                                      ,'CVC-ETH'
                                      ,'CVT-BTC'
                                      ,'DAI-BTC'
                                      ,'DAI-ETH'
                                      ,'DAI-USD'
                                      ,'DAI-USDT'
                                      ,'DASH-BTC'
                                      ,'DASH-ETH'
                                      ,'DASH-USD'
                                      ,'DASH-USDT'
                                      ,'DAWN-BTC'
                                      ,'DCR-BTC'
                                      ,'DCR-USD'
                                      ,'DCR-USDT'
                                      ,'DEP-BTC'
                                      ,'DEP-USDT'
                                      ,'DFI-BTC'
                                      ,'DFI-USDT'
                                      ,'DGB-BTC'
                                      ,'DGB-ETH'
                                      ,'DGB-USD'
                                      ,'DGB-USDT'
                                      ,'DMT-BTC'
                                      ,'DMT-ETH'
                                      ,'DNA-BTC'
                                      ,'DNA-USDT'
                                      ,'DNT-BTC'
                                      ,'DOGE-BTC'
                                      ,'DOGE-ETH'
                                      ,'DOGE-USD'
                                      ,'DOGE-USDT'
                                      ,'DOT-BTC'
                                      ,'DOT-ETH'
                                      ,'DOT-EUR'
                                      ,'DOT-USD'
                                      ,'DOT-USDT'
                                      ,'DRGN-BTC'
                                      ,'DTA-BTC'
                                      ,'DUCATO-BTC'
                                      ,'DUSK-BTC'
                                      ,'ECELL-BTC'
                                      ,'ECELL-USDT'
                                      ,'ECOC-BTC'
                                      ,'ECOC-USDT'
                                      ,'EDR-BTC'
                                      ,'ELA-BTC'
                                      ,'ELAMA-BTC'
                                      ,'ELA-USDT'
                                      ,'EMC2-BTC'
                                      ,'ENG-BTC'
                                      ,'ENG-ETH'
                                      ,'ENJ-BTC'
                                      ,'ENJ-ETH'
                                      ,'ENJ-USD'
                                      ,'ENJ-USDT'
                                      ,'EOS-BTC'
                                      ,'EOS-ETH'
                                      ,'EOS-USD'
                                      ,'EOS-USDT'
                                      ,'ETC-BTC'
                                      ,'ETC-ETH'
                                      ,'ETC-USD'
                                      ,'ETC-USDT'
                                      ,'ETHBEAR-USD'
                                      ,'ETHBEAR-USDT'
                                      ,'ETH-BTC'
                                      ,'ETHBULL-USD'
                                      ,'ETHBULL-USDT'
                                      ,'ETH-EUR'
                                      ,'ETH-USD'
                                      ,'ETH-USDT'
                                      ,'EXCL-BTC'
                                      ,'EXE-BTC'
                                      ,'EXE-USDT'
                                      ,'EXP-BTC'
                                      ,'FB-BTC'
                                      ,'FB-USD'
                                      ,'FB-USDT'
                                      ,'FCT2-BTC'
                                      ,'FCT-BTC'
                                      ,'FIL-BTC'
                                      ,'FIL-ETH'
                                      ,'FIL-USD'
                                      ,'FIL-USDT'
                                      ,'FIRO-BTC'
                                      ,'FIT-BTC'
                                      ,'FLETA-BTC'
                                      ,'FLO-BTC'
                                      ,'FME-BTC'
                                      ,'FME-USDT'
                                      ,'FNB-BTC'
                                      ,'FOR-BTC'
                                      ,'FRSP-BTC'
                                      ,'FSN-BTC'
                                      ,'FTC-BTC'
                                      ,'FX-BTC'
                                      ,'FX-ETH'
                                      ,'GAME-BTC'
                                      ,'GBYTE-BTC'
                                      ,'GEO-BTC'
                                      ,'GLEEC-BTC'
                                      ,'GLM-BTC'
                                      ,'GLM-ETH'
                                      ,'GNC-BTC'
                                      ,'GNC-USDT'
                                      ,'GNO-BTC'
                                      ,'GNO-ETH'
                                      ,'GO-BTC'
                                      ,'GOOGL-BTC'
                                      ,'GOOGL-USD'
                                      ,'GOOGL-USDT'
                                      ,'GRIN-BTC'
                                      ,'GRIN-USDT'
                                      ,'GRS-BTC'
                                      ,'GRT-BTC'
                                      ,'GRT-ETH'
                                      ,'GRT-EUR'
                                      ,'GRT-USD'
                                      ,'GRT-USDT'
                                      ,'GST-BTC'
                                      ,'GST-USDT'
                                      ,'GTO-BTC'
                                      ,'GXC-BTC'
                                      ,'GXC-USDT'
                                      ,'HBAR-BTC'
                                      ,'HBAR-ETH'
                                      ,'HBAR-USD'
                                      ,'HBAR-USDT'
                                      ,'HBD-BTC'
                                      ,'HDAC-BTC'
                                      ,'HDAO-BTC'
                                      ,'HDAO-USDT'
                                      ,'HEDG-BTC'
                                      ,'HIVE-BTC'
                                      ,'HIVE-USD'
                                      ,'HIVE-USDT'
                                      ,'HMQ-BTC'
                                      ,'HNS-BTC'
                                      ,'HNS-ETH'
                                      ,'HNS-USDT'
                                      ,'HXRO-BTC'
                                      ,'HXRO-USDT'
                                      ,'HYDRO-BTC'
                                      ,'ICX-BTC'
                                      ,'IGNIS-BTC'
                                      ,'INSTAR-BTC'
                                      ,'INX-BTC'
                                      ,'INX-USDT'
                                      ,'IOC-BTC'
                                      ,'IOST-BTC'
                                      ,'IOTA-BTC'
                                      ,'IOTX-BTC'
                                      ,'IRIS-BTC'
                                      ,'IRIS-USDT'
                                      ,'JNT-BTC'
                                      ,'KAI-BTC'
                                      ,'KAI-USDT'
                                      ,'KDA-BTC'
                                      ,'KDAG-BTC'
                                      ,'KDAG-USDT'
                                      ,'KDA-USDT'
                                      ,'KLAY-BTC'
                                      ,'KLAY-USDT'
                                      ,'KLV-BTC'
                                      ,'KLV-USDT'
                                      ,'KMD-BTC'
                                      ,'KMD-USD'
                                      ,'KNC-BTC'
                                      ,'KNC-ETH'
                                      ,'KNC-EUR'
                                      ,'KNC-USD'
                                      ,'KNC-USDT'
                                      ,'KOK-BTC'
                                      ,'KOK-USDT'
                                      ,'KRT-BTC'
                                      ,'KRT-USDT'
                                      ,'KSM-BTC'
                                      ,'KSM-ETH'
                                      ,'KSM-USDT'
                                      ,'LAMB-BTC'
                                      ,'LBC-BTC'
                                      ,'LBC-USDT'
                                      ,'LCS-BTC'
                                      ,'LCS-USDT'
                                      ,'LINK-BTC'
                                      ,'LINK-ETH'
                                      ,'LINK-USD'
                                      ,'LINK-USDT'
                                      ,'LMCH-BTC'
                                      ,'LMCH-USDT'
                                      ,'LOKI-BTC'
                                      ,'LOKI-USDT'
                                      ,'LOOM-BTC'
                                      ,'LOON-BTC'
                                      ,'LOON-USDT'
                                      ,'LRC-BTC'
                                      ,'LSK-BTC'
                                      ,'LTC-BTC'
                                      ,'LTC-ETH'
                                      ,'LTC-USD'
                                      ,'LTC-USDT'
                                      ,'LUCY-BTC'
                                      ,'LUCY-USDT'
                                      ,'LUNA-BTC'
                                      ,'LUNA-USDT'
                                      ,'MAID-BTC'
                                      ,'MANA-BTC'
                                      ,'MANA-ETH'
                                      ,'MARO-BTC'
                                      ,'MATIC-BTC'
                                      ,'MATIC-USDT'
                                      ,'MDT-BTC'
                                      ,'MDT-USDT'
                                      ,'ME-BTC'
                                      ,'MED-BTC'
                                      ,'MEME-BTC'
                                      ,'MER-BTC'
                                      ,'META-BTC'
                                      ,'MET-BTC'
                                      ,'MET-ETH'
                                      ,'MFA-BTC'
                                      ,'MFA-USDT'
                                      ,'MFT-BTC'
                                      ,'MKR-BTC'
                                      ,'MKR-ETH'
                                      ,'MKR-USDT'
                                      ,'MOC-BTC'
                                      ,'MOF-BTC'
                                      ,'MOF-USDT'
                                      ,'MONA-BTC'
                                      ,'MORE-BTC'
                                      ,'MRPH-BTC'
                                      ,'MTL-BTC'
                                      ,'MUE-BTC'
                                      ,'NAV-BTC'
                                      ,'NEO-BTC'
                                      ,'NEO-ETH'
                                      ,'NEO-USDT'
                                      ,'NFLX-BTC'
                                      ,'NFLX-USD'
                                      ,'NFLX-USDT'
                                      ,'NGC-BTC'
                                      ,'NKN-BTC'
                                      ,'NLG-BTC'
                                      ,'NMR-BTC'
                                      ,'NMR-ETH'
                                      ,'NMR-USDT'
                                      ,'NPXS-BTC'
                                      ,'NPXS-ETH'
                                      ,'NPXS-USDT'
                                      ,'NVT-BTC'
                                      ,'NVT-USDT'
                                      ,'NXS-BTC'
                                      ,'NXT-BTC'
                                      ,'OCEAN-BTC'
                                      ,'OCEAN-USDT'
                                      ,'OGN-BTC'
                                      ,'OGN-ETH'
                                      ,'OK-BTC'
                                      ,'OMG-BTC'
                                      ,'OMG-ETH'
                                      ,'OMG-USDT'
                                      ,'ONG-BTC'
                                      ,'ONT-BTC'
                                      ,'ONT-USDT'
                                      ,'ORBS-BTC'
                                      ,'OXT-BTC'
                                      ,'OXT-USDT'
                                      ,'PART-BTC'
                                      ,'PAX-BTC'
                                      ,'PAX-USD'
                                      ,'PAY-BTC'
                                      ,'PAY-ETH'
                                      ,'PFE-BTC'
                                      ,'PFE-USD'
                                      ,'PFE-USDT'
                                      ,'PHNX-BTC'
                                      ,'PI-BTC'
                                      ,'PINK-BTC'
                                      ,'PIVX-BTC'
                                      ,'PLA-BTC'
                                      ,'PMA-BTC'
                                      ,'PMA-USDT'
                                      ,'POT-BTC'
                                      ,'POWR-BTC'
                                      ,'POWR-ETH'
                                      ,'PPC-BTC'
                                      ,'PROM-BTC'
                                      ,'PTON-BTC'
                                      ,'PTOY-BTC'
                                      ,'PXL-BTC'
                                      ,'QLC-BTC'
                                      ,'QLC-USDT'
                                      ,'QNT-BTC'
                                      ,'QRL-BTC'
                                      ,'QTUM-BTC'
                                      ,'QTUM-ETH'
                                      ,'RCN-BTC'
                                      ,'RDD-BTC'
                                      ,'REN-BTC'
                                      ,'RENBTC-BTC'
                                      ,'RENBTC-ETH'
                                      ,'RENBTC-EUR'
                                      ,'RENBTC-USD'
                                      ,'RENBTC-USDT'
                                      ,'REN-ETH'
                                      ,'REN-EUR'
                                      ,'REN-USD'
                                      ,'REN-USDT'
                                      ,'REPV2-BTC'
                                      ,'REPV2-ETH'
                                      ,'REV-BTC'
                                      ,'REV-USDT'
                                      ,'RLC-BTC'
                                      ,'RVC-BTC'
                                      ,'RVC-USDT'
                                      ,'RVN-BTC'
                                      ,'RVN-USD'
                                      ,'RVN-USDT'
                                      ,'SBD-BTC'
                                      ,'SC-BTC'
                                      ,'SC-ETH'
                                      ,'SC-USD'
                                      ,'SC-USDT'
                                      ,'SDT-BTC'
                                      ,'SDT-USDT'
                                      ,'SENSO-BTC'
                                      ,'SENSO-ETH'
                                      ,'SG-BTC'
                                      ,'SG-USDT'
                                      ,'SHR-BTC'
                                      ,'SHR-USDT'
                                      ,'SIB-BTC'
                                      ,'SIX-BTC'
                                      ,'SKM-BTC'
                                      ,'SKM-USDT'
                                      ,'SLS-BTC'
                                      ,'SNT-BTC'
                                      ,'SNT-ETH'
                                      ,'SOLVE-BTC'
                                      ,'SOLVE-ETH'
                                      ,'SOLVE-USD'
                                      ,'SOLVE-USDT'
                                      ,'SPC-BTC'
                                      ,'SPHR-BTC'
                                      ,'SPIN-BTC'
                                      ,'SPND-BTC'
                                      ,'SPY-BTC'
                                      ,'SPY-USD'
                                      ,'SPY-USDT'
                                      ,'SRN-BTC'
                                      ,'SRN-ETH'
                                      ,'STC-BTC'
                                      ,'STEEM-BTC'
                                      ,'STMX-BTC'
                                      ,'STMX-ETH'
                                      ,'STORJ-BTC'
                                      ,'STPT-BTC'
                                      ,'STRAX-BTC'
                                      ,'STRAX-ETH'
                                      ,'SUKU-BTC'
                                      ,'SUKU-USDT'
                                      ,'SUTER-BTC'
                                      ,'SUTER-USDT'
                                      ,'SXP-BTC'
                                      ,'SYS-BTC'
                                      ,'TEA-BTC'
                                      ,'TEA-USDT'
                                      ,'TEMCO-BTC'
                                      ,'THC-BTC'
                                      ,'TNC-BTC'
                                      ,'TRAC-BTC'
                                      ,'TRAC-ETH'
                                      ,'TRAC-USDT'
                                      ,'TRX-BTC'
                                      ,'TRX-ETH'
                                      ,'TRX-EUR'
                                      ,'TRX-USD'
                                      ,'TRX-USDT'
                                      ,'TRYB-BTC'
                                      ,'TRYB-USDT'
                                      ,'TSHP-BTC'
                                      ,'TSLA-BTC'
                                      ,'TSLA-USD'
                                      ,'TSLA-USDT'
                                      ,'TUBE-BTC'
                                      ,'TUDA-BTC'
                                      ,'TUSD-BTC'
                                      ,'TUSD-ETH'
                                      ,'TUSD-USD'
                                      ,'TUSD-USDT'
                                      ,'UBQ-BTC'
                                      ,'UBT-BTC'
                                      ,'UBT-ETH'
                                      ,'UCT-BTC'
                                      ,'UCT-USDT'
                                      ,'UMA-BTC'
                                      ,'UMA-ETH'
                                      ,'UMA-EUR'
                                      ,'UMA-USD'
                                      ,'UMA-USDT'
                                      ,'UNI-BTC'
                                      ,'UNI-ETH'
                                      ,'UNI-USD'
                                      ,'UNI-USDT'
                                      ,'UPEUR-BTC'
                                      ,'UPP-BTC'
                                      ,'UPT-BTC'
                                      ,'UPUSD-BTC'
                                      ,'UPUSD-USDT'
                                      ,'UPXAU-BTC'
                                      ,'UPXAU-USDT'
                                      ,'UQC-BTC'
                                      ,'UQC-USDT'
                                      ,'URAC-BTC'
                                      ,'USDC-BTC'
                                      ,'USDC-ETH'
                                      ,'USDC-USD'
                                      ,'USDC-USDT'
                                      ,'USD-EUR'
                                      ,'USDN-BTC'
                                      ,'USDN-USDT'
                                      ,'USDS-BTC'
                                      ,'USDS-USD'
                                      ,'USDT-EUR'
                                      ,'USDT-USD'
                                      ,'UST-BTC'
                                      ,'UST-USDT'
                                      ,'UTI-BTC'
                                      ,'UTK-BTC'
                                      ,'VAL-BTC'
                                      ,'VANY-BTC'
                                      ,'VANY-USDT'
                                      ,'VBK-BTC'
                                      ,'VDX-BTC'
                                      ,'VDX-ETH'
                                      ,'VDX-USDT'
                                      ,'VEE-BTC'
                                      ,'VET-BTC'
                                      ,'VET-USDT'
                                      ,'VIA-BTC'
                                      ,'VIB-BTC'
                                      ,'VIB-ETH'
                                      ,'VID-BTC'
                                      ,'VITE-BTC'
                                      ,'VLX-BTC'
                                      ,'VLX-USDT'
                                      ,'VRA-BTC'
                                      ,'VRC-BTC'
                                      ,'VTC-BTC'
                                      ,'WAVES-BTC'
                                      ,'WAVES-ETH'
                                      ,'WAXP-BTC'
                                      ,'WAXP-ETH'
                                      ,'WAXP-USD'
                                      ,'WAXP-USDT'
                                      ,'WBTC-BTC'
                                      ,'WBTC-ETH'
                                      ,'WBTC-USDT'
                                      ,'WGP-BTC'
                                      ,'WICC-BTC'
                                      ,'WICC-USDT'
                                      ,'WINGS-BTC'
                                      ,'XDN-BTC'
                                      ,'XEM-BTC'
                                      ,'XEM-ETH'
                                      ,'XHV-BTC'
                                      ,'XLM-BTC'
                                      ,'XLM-ETH'
                                      ,'XLM-EUR'
                                      ,'XLM-USD'
                                      ,'XLM-USDT'
                                      ,'XMR-BTC'
                                      ,'XMR-ETH'
                                      ,'XMR-USDT'
                                      ,'XMY-BTC'
                                      ,'XRP-BTC'
                                      ,'XRP-ETH'
                                      ,'XRP-EUR'
                                      ,'XRP-USD'
                                      ,'XRP-USDT'
                                      ,'XST-BTC'
                                      ,'XTP-BTC'
                                      ,'XTZ-BTC'
                                      ,'XTZ-ETH'
                                      ,'XTZ-USD'
                                      ,'XTZ-USDT'
                                      ,'XUC-BTC'
                                      ,'XUC-USDT'
                                      ,'XVG-BTC'
                                      ,'XVG-USDT'
                                      ,'XWC-BTC'
                                      ,'XWC-USDT'
                                      ,'YFL-BTC'
                                      ,'YFL-ETH'
                                      ,'YFL-EUR'
                                      ,'YFL-USD'
                                      ,'YFL-USDT'
                                      ,'YOU-BTC'
                                      ,'ZEC-BTC'
                                      ,'ZEC-ETH'
                                      ,'ZEC-USD'
                                      ,'ZEC-USDT'
                                      ,'ZEN-BTC'
                                      ,'ZEN-USD'
                                      ,'ZIL-BTC'
                                      ,'ZRX-BTC'
                                      ,'ZRX-ETH'
                                      ,'ZRX-USD'
                                      ,'ZRX-USDT'
]
=======
        self.names               = ['ETH', 'XRP', 'LTC', 'USDT', 'BCH', 'LIBRA', 'XMR', 'EOS', 'BSV', 'BNB', 'BTC', 'USD', 'EUR', 'USDC', 'USDT']        
        self.all_triangles       = []
        self.unique_combinations = []
>>>>>>> c1b7500202f28ca28b6a109360763fd79a822f04
    
        #Run Functions 
        self.unique_triangles()
        self.fix_all_triangles()
        

    def unique_triangles(self):
             
        list_of_names = self.names
        
        list_final = list(itertools.combinations(list_of_names, 3))
        
        self.all_triangles = list_final

    def fix_all_triangles(self):
        
        for tr in self.all_triangles:
            
            comb = list(permutations([tr[0], tr[1], tr[2]], 3))
            
            for elem in comb:
                
                safe_coin = ['USD','EUR','USDT','USDC']
                
                if elem[0] in safe_coin :
                        if elem[1]+'-'+elem[0] in self.possible_combinations and elem[2]+'-'+elem[1] in self.possible_combinations and  elem[2]+'-'+elem[0] in self.possible_combinations:
                            self.unique_combinations.append([elem[1]+'-'+elem[0], elem[2]+'-'+elem[1], elem[2]+'-'+elem[0], 0])
                

def return_all_triangles_list():

    a          = all_combos()
    res        = a.unique_combinations  
    
    return res




if __name__ == "__main__":
    
    
    print('\n"""""""""""""""""""""""""""""""""""""\n')
    
    res = return_all_triangles_list()
<<<<<<< HEAD
    df = pd.DataFrame (res,columns=['TickerPairA','TickerPairB','TickerPairC','Route'])
    df.to_csv('all_triangulars_arbitrage.csv')
    
=======
>>>>>>> c1b7500202f28ca28b6a109360763fd79a822f04
    
    for i in range (0,len(res)):
        print(str(i) + str(res[i]))
        
<<<<<<< HEAD
    print('\n"""""""""""""""""""""""""""""""""""""\n')
=======
    print('\n"""""""""""""""""""""""""""""""""""""\n')






>>>>>>> c1b7500202f28ca28b6a109360763fd79a822f04
